### DISCUSSION TITLE
how to put elements and text together on stencil paper

### DISCUSSION THREAD

**Discussion by vyshak-pr** [clientIO/joint#1965] [Q&A]
![svg](https://user-images.githubusercontent.com/120721238/209769475-b9355375-54d9-4055-bb42-86f9742de2de.png)

how to achieve this kind of collapsible structure?
how to put elements and text together on stencil paper

**Comment by kumilingus** [comment]
You need to add  elements with the text positioned on the right side (the same way you'd add them to the usual paper).
You can define the stencil groups if you want to create the collapsible sections (for that please refer to the `ui.Stencil` [documentation](https://resources.jointjs.com/docs/rappid/v3.6/ui.Stencil.html#ui.Stencil)).

*Note: The KitchenSink application hides all `<text>` elements in the stencil with CSS.*

```CSS
.joint-stencil .joint-element[data-type="standard.Image"] text,
.joint-stencil .joint-element[data-type="standard.Cylinder"] text,
.joint-stencil .joint-element[data-type="standard.InscribedImage"] text,
.joint-stencil .joint-element[data-type="devs.Atomic"] .inPorts text,
.joint-stencil .joint-element[data-type="devs.Atomic"] .outPorts text,
.joint-stencil .joint-element[data-type="pn.Transition"] text,
.joint-stencil .joint-element .joint-port text {
    display: none;
}
```
