### ISSUE TITLE
SVG's height is overlapped by uikit.js

### ISSUE THREAD

**Issue by vkcorp** [clientIO/joint#2510]
### What happened?

I'm using jointjs@3.7.7 with uikit@3.16.22, and found an error in my sample code.
As I attched my sample code,
I tried to draw a rect in my paper, but the bottom of my rect was cut.
After tracking, I found SVG's height was overlapped by Uikit.

[jointjs1.zip](https://github.com/clientIO/joint/files/14096712/jointjs1.zip)

### Version

3.7.7

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### What operating system are you seeing the problem on?

Windows

**Comment by kumilingus** [comment]
It's not a bug in *JointJS*.

The **uikit** CSS is too generic and affects the JointJS paper `svg`.

```css
/* uikit.css */
canvas, img, svg, video {
    max-width: 100%;
    height: auto;
    box-sizing: border-box;
}
```

Adding the following CSS to your application will solve the issue.

```css
.joint-paper svg { height: 100%; }
```
