### ISSUE TITLE
zoomToFit produces weird results in Firefox

### ISSUE THREAD

**Issue by nico-onmap** [clientIO/joint#693]
The `paperScroller.zoomToFit()` method seems to zoomOut when it's not needed in Firefox.

How to reproduce?

Open the [BPMN Demo](http://resources.jointjs.com/demos/rappid/apps/BPMNEditor/index.html), and call this in the devtools:

```js
paperScroller.zoomToFit()
```

Compare the results with Chrome or Edge.

**Comment by kumilingus** [comment]
Hi Nico, I had no luck reproducing this issue. What version of FF do you use? Could you also send us some screenshots please. Thank you.

**Comment by nico-onmap** [comment]
I tried with Firefox 57b and latest official release, as well as with version 50.

Here are two screenshots of Chrome & Firefox showing the BPMN demo after calling `paperScroller.zoomToFit()`:

![chrome_2017-10-05_16-54-22](https://user-images.githubusercontent.com/26772786/31234308-dc932d18-a9ee-11e7-846d-bd7609617f94.png)

![firefox_2017-10-05_16-53-34](https://user-images.githubusercontent.com/26772786/31234313-e08b87b2-a9ee-11e7-89a0-331be72a62e7.png)


As you can see the zoomLevel isn't the same and the graph appears smaller in Firefox, although both Windows have the same size. Depending on the model this can make a huge difference, and while the graph appears readble on Chrome, it's so small that it's not readable on Firefox.

**Comment by kumilingus** [comment]
It seems it's specifically Windows - Firefox problem (I can't reproduce this on OS X). Let us investigate more and we get back to you about this. Thank you for reporting this.

**Comment by kumilingus** [comment]
It's a regression. Please update the following rule in `bpmn.css`.
```css
/* Hide "empty" paths as firefox returns a huge bounding box for them. */
  @-moz-document url-prefix() {
    .joint-theme-bpmn .joint-link .marker-source[d="M 0 0"],
    .joint-theme-bpmn .joint-link .marker-target[d="M 0 0"] {
          display: none;
    }
  }
```
