### ISSUE TITLE
Huge highlighted outline on Chrome

### ISSUE THREAD

**Issue by crystalfp** [clientIO/joint#84]
I had to add to my css the following:

``` css
.element.highlighted {
  outline: none
}
```

Otherwise on Chrome a very large outline appears around the node when I execute `highlight()`

So seems line 200 in joint.css puts the outline around an unintended bounding box.
